
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
  server:
    cors:
      enabled: true
  application:
    name: chuu-api
  caches:
    command-info:
      maximum-size: 1
    authorization:
  http:
    client:
      log-level: info
chuu:
  path_to_commands: commands.json
  client_id: 537353774205894676
  client_secret: vLwVJv4XJkff9rtLJL2w5xfHJnWt4_cZ
endpoints:
  all:
    enabled: true
    sensitive: false
