micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne

    endpoints:
      login:
        enabled: true
      router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
  application:
    name: web
  caches:
    command-info:
      maximum-size: 1
    authorization:



chuu:
  path_to_commands: ../commands.json
  client_id: 537353774205894676
  client_secret: vLwVJv4XJkff9rtLJL2w5xfHJnWt4_cZ
endpoints:
  all:
    enabled: true
    sensitive: false
